version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - odoo
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    depends_on:
      - odoo
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  odoo:
    image: odoo:13.0
    container_name: odoo
    depends_on:
      - db
    ports:
      - 8069:8069
      - 8072:8072
    volumes:
      - addons:/mnt/extra-addons:ro,Z
      - ./config:/etc/odoo
    # command: odoo -u all -d odoo
  
  db:
    image: postgres:12
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - odoo-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres

volumes:
  addons:
  odoo-db: